# Generated by Django 3.2.3 on 2021-05-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualartworkform',
            name='nature_of_authorship',
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualartworkform',
            name='option8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='virtualartworkform',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
