# Generated by Django 3.2.3 on 2021-05-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210528_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option1',
            new_name='dimensional_artwork',
        ),
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option2',
            new_name='dimensional_sculpture',
        ),
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option3',
            new_name='jewelery_design',
        ),
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option4',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option5',
            new_name='photograph',
        ),
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option6',
            new_name='reproduction_of_artwork',
        ),
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option7',
            new_name='technical_drawing',
        ),
        migrations.RenameField(
            model_name='virtualartworkform',
            old_name='option8',
            new_name='text',
        ),
    ]
