# Generated by Django 3.2.3 on 2021-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20210530_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialworkform',
            name='date_of_employing_copyright',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialworkform',
            name='date_of_hiring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialworkform',
            name='employer_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soundrecordingform',
            name='date_of_employing_copyright',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soundrecordingform',
            name='date_of_hiring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualartworkform',
            name='date_of_employing_copyright',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualartworkform',
            name='date_of_hiring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualartworkform',
            name='employer_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
