# Generated by Django 3.1.6 on 2021-02-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureOfAuthorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.BooleanField()),
                ('two', models.BooleanField()),
                ('three', models.BooleanField()),
                ('four', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Awein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.natureofauthorship')),
            ],
        ),
    ]
