# Generated by Django 3.2.3 on 2021-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210528_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualartworkform',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
