# Generated by Django 3.2.3 on 2021-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_virtualartworkform_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundrecordingform',
            old_name='date_of_authorship',
            new_name='city',
        ),
        migrations.AddField(
            model_name='soundrecordingform',
            name='day',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='soundrecordingform',
            name='month',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='soundrecordingform',
            name='state',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='soundrecordingform',
            name='year',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='soundrecordingform',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
