# Generated by Django 3.2.3 on 2021-05-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210529_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serialworkform',
            old_name='date_of_authorship',
            new_name='city',
        ),
        migrations.AddField(
            model_name='serialworkform',
            name='day',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='serialworkform',
            name='month',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='serialworkform',
            name='state',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='serialworkform',
            name='year',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='serialworkform',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='soundrecordingform',
            name='employer_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
