# Generated by Django 3.2.3 on 2021-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20210616_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literaryworkform',
            name='date_of_authorship',
        ),
        migrations.AddField(
            model_name='literaryworkform',
            name='day',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='literaryworkform',
            name='month',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='literaryworkform',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='literaryworkform',
            name='date_of_employing_copyright',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literaryworkform',
            name='date_of_hiring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literaryworkform',
            name='employer_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literaryworkform',
            name='issue_date',
            field=models.DateField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='performingartform',
            name='date_of_employing_copyright',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performingartform',
            name='date_of_hiring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performingartform',
            name='employer_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
